kind: Service                             
apiVersion: v1
metadata:
  name: supreetr
  labels:
    app: supreetr
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: supreetr
  type: LoadBalancer                   
